<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Weekly Report - Week {{ $report->week_number }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .title {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }

        .subtitle {
            font-size: 16px;
            color: #666;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        .summary {
            background-color: #f9f9f9;
            padding: 15px;
            margin: 20px 0;
            border-radius: 5px;
        }

        .footer {
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: #999;
        }

        .badge {
            padding: 5px 10px;
            border-radius: 5px;
            color: white;
            display: inline-block;
        }

        .bg-green {
            background-color: #4CAF50;
        }

        .bg-red {
            background-color: #f44336;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="title"> Weekly Sales Report</div>
        <div class="subtitle">
            Period: {{ $report->week_start_date }} → {{ $report->week_end_date }}
        </div>
        <div class="subtitle">Generated: {{ $generated_at }}</div>
    </div>

    <div class="summary">
        <h3>Sales Summary</h3>
        <table>
            <tr>
                <th>Total Orders</th>
                <th>Total Sales</th>
                <th>Average Order Value</th>
            </tr>
            <tr>
                <td>{{ number_format($report->total_orders) }}</td>
                <td>${{ number_format($report->total_sales, 2) }}</td>
                <td>${{ number_format($report->average_order_value, 2) }}</td>
            </tr>
        </table>
    </div>

    <div class="summary">
        <h3> Top & Bottom Products</h3>
        <table>
            <tr>
                <th></th>
                <th>Product Name</th>
                <th>Quantity Sold</th>
            </tr>
            <tr>
                <td><span class="badge bg-green">Top Product</span></td>
                <td>{{ $report->top_product_name }}</td>
                <td>{{ number_format($report->top_product_quantity) }}</td>
            </tr>
            <tr>
                <td><span class="badge bg-red">Bottom Product</span></td>
                <td>{{ $report->bottom_product_name }}</td>
                <td>{{ number_format($report->bottom_product_quantity) }}</td>
            </tr>
        </table>

    </div>
    <!-- بعد جدول Top & Bottom Products، أضف هذا: -->

    <div class="summary">
        <h3> All Products Sales Breakdown </h3>
        <table>
            <thead>
                <tr>
                    <th>Rank</th>
                    <th>Product Name</th>
                    <th>Quantity Sold</th>
                    <th>Total Revenue</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($report->productStats()->orderBy('rank')->get() as $stat)
                    <tr>
                        <td>#{{ $stat->rank }}</td>
                        <td>{{ $stat->product_name }}</td>
                        <td>{{ number_format($stat->quantity_sold) }}</td>
                        <td>${{ number_format($stat->total_revenue, 2) }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="footer">
        This report was automatically generated by the Batch Processing System
    </div>
</body>

</html>
